#! /usr/bin/env ruby

require 'csv'
data_file = File.expand_path "./data/domains.csv"
data = CSV.read(data_file, headers: true)

puts data.count
data = data.reject { |row| row["live"] == "false" }
puts data.count

CSV.open(data_file, "wb") do |csv|
  csv << data.first.to_h.keys
  data.each do |row|
    csv << row
  end
end
